### ISSUE TITLE
Add a linter

### ISSUE THREAD

**Issue by franzejr** [arthurpaulino/empr#2]
You should use [Prettier](https://github.com/prettier/prettier) in this project, or use another link. I'd prefer prettier, because you can also set it up in your text editor and automatically edit your file.

**Comment by arthurpaulino** [comment]
[done](https://github.com/arthurpaulino/empr/commit/a5663c06c16beea6d589081f8834302d1794e83d)

**Comment by franzejr** [comment]
Nice. From now on, you can use prettier in your text editor and make it running after each saving.

@arthurpaulino .
